### ISSUE TITLE
Not working with esp32-audiokit-voice-assistant.yaml

### ISSUE THREAD

**Issue by yellow-sky** [sehraf/esphome-components#1]
[20:50:00][C][audio:107]: Setting up Audio...
[20:50:00][C][i2s_audio.speaker:019]: Setting up I2S Audio Speaker...
[20:50:00][C][AC101:054]: Setting up AC101...
[20:50:00][E][component:113]: Component ac101 was marked as failed.

**Comment by sehraf** [comment]
is your i2c working? (or your ESP has no AC101 :smile: )

**Comment by yellow-sky** [comment]
code, logs and board in attach. maybe new version of esphome?
[logs_iot-esp32-audio_run.txt](https://github.com/sehraf/esphome-components/files/11778435/logs_iot-esp32-audio_run.txt)
![photo_2023-06-17_12-06-48](https://github.com/sehraf/esphome-components/assets/1277422/87f2cb7a-dbac-4601-b6e0-ba7a2bd1a7e4)
[code.txt](https://github.com/sehraf/esphome-components/files/11778440/code.txt)

**Comment by sehraf** [comment]
Thanks, i see the problem:
> [11:56:48][I][i2c.arduino:075]: Found i2c device at address 0x10

The ESP32 AudioKits come in two flavors
1) the "origial" one with AC101, and 
2) the later one with an ES8388 instead (due to chip shortage)

Yours seems to be the latter with ES8388, which has an i2c address of `0x10` https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/blob/master/PlatformIO/src/devices/ES8388Control.cpp#L5

Try https://github.com/esphome/esphome/pull/3552 instead
```yaml
external_components:
  - source: github://pr#3552
    components: [es8388]

es8388:
```

**Comment by George1422** [comment]
I have the same audio kit board as you with the ES8388 DAC (I think, clones will be clones). I noticed that you are using different gpio pins that what I have in my configuration. 

```

external_components:
  - source: github://pr#3552
    components: [es8388]

es8388:

i2c:
  sda: GPIO33
  scl: GPIO32
  scan: true
  id: bus_a
      
i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO27

microphone:
  - platform: i2s_audio
    i2s_din_pin: GPIO35
    channel: left
    id: mic1
    adc_type: external
    pdm: false

speaker:
  - platform: i2s_audio
    id: speaker1
    dac_type: external
    i2s_dout_pin: GPIO26
    mode: mono
  
media_player:
  - platform: i2s_audio
    dac_type: external
    name: "${dev_name}"
    id: AudioPlayer
    i2s_dout_pin: GPIO26
    mode: stereo
    mute_pin:
      number: GPIO21
      inverted: true
```
Specifically around the LR Clock and the data out pins. I do have it working and plays audio just fine. I'm interested in hearing your experiences with this board. I could not get the mic/assistant bits to work.
